server:
  port: 6666

spring:
  activemq:
    broker-url: tcp://192.168.1.101:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false

myqueue: sprintboot-queue
mytopic: sprintboot-topic